### ISSUE TITLE
Screenshot Done : Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "top-left-xxtop-left-y+the result x+the result y" "answers.jpg" this most likely means the gm/convert binaries can't be found

### ISSUE THREAD

**Issue by desireend** [maxenxe/HQ-Trivia-Bot#2]

**Comment by maxenxe** [comment]
Try reinstalling it ( `npm install -g gm`)

**Comment by desireend** [comment]
Nope. It still is giving issues.

**Comment by maxenxe** [comment]
If you're using Windows add gm to your PATH, follow the process given in the last closed issue

**Comment by desireend** [comment]
I am still confused. Please email me to explain into detail.

**Comment by Anishrajeev210** [comment]
I am getting same error but i am on iphone 6 and mac

**Comment by Anishrajeev210** [comment]
can anyone help

**Comment by Anishrajeev210** [comment]
Anishs-MacBook-Pro:HQ-Trivia-Bot-master anish$ npm start

> hqtriviabot@1.0.0 start /Users/anish/Downloads/HQ-Trivia-Bot-master
> node bot.js

Screenshot done
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "351x233+606+334" "answers.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/anish/Downloads/HQ-Trivia-Bot-master/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by chaoscreater** [comment]
There needs to be better instructions / documentations. Tried reinstalling with npm install -g gm and still not working. No errors found in reinstallation.

I've added W:\HQ-Trivia-Bot-master\node_modules\gm to the environmental path already, still doesn't work.

**Comment by chaoscreater** [comment]
I've gotten it to work. Download this:
http://www.graphicsmagick.org/

It should be a .exe that you install for Windows. During the installation step, it'll ask you to add to environmental path.

Close your powershell / command prompt and relaunch it and run node bot.js. It should work now and generate a answers.jpg in the same folder.

**Comment by maxenxe** [comment]
Hey, the bot research the question and look for number of occurrences for the answer, if it finds a Wikipedia website it search on the page for answers, I agree that the OCR is not really accurate but, did it for the fun 🙃

**Comment by tdaddy** [comment]
did everything @chaoscreater said to do and still get this error

Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\Topher\AppData\Local\Tem
p\tmp-1876L7qoo2V9IDKS'
node-tesseract: Preprocessor cleanup
{ Error: Command failed: tesseract answers.jpg C:\Users\Topher\AppData\Local\Tem
p\tmp-1876L7qoo2V9IDKS
'tesseract' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract answers.jpg C:\\Users\\Topher\\AppData\\Local\\Temp\\tmp-1876L
7qoo2V9IDKS' }

**Comment by maxenxe** [comment]
If you look to your error it isn't the same, your error is because of tesseract, you must add tesseract to your environment variables, please take a look to the previous issues for further solutions

**Comment by maxenxe** [comment]
(https://github.com/maxenxe/HQ-Trivia-Bot/issues/1)

**Comment by tdaddy** [comment]
i did everything in the previous issues too

**Comment by maxenxe** [comment]
Can you copy/paste here your PATH ?
